// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxE8dTniE20e2XfQiJ5z_gIM1JI1-7y0s',
    appId: '1:539777077394:web:e53435915d3c5c4f61d64b',
    messagingSenderId: '539777077394',
    projectId: 'instagram-cdabc',
    authDomain: 'instagram-cdabc.firebaseapp.com',
    storageBucket: 'instagram-cdabc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMT9LCkkeMDQD-pBA7UxHyayY486u1Wdk',
    appId: '1:539777077394:android:4677c49150c32f9561d64b',
    messagingSenderId: '539777077394',
    projectId: 'instagram-cdabc',
    storageBucket: 'instagram-cdabc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyTouEQv0pC1CN39x-ztaYAjW91mAjeeA',
    appId: '1:539777077394:ios:787031c435ad9ce061d64b',
    messagingSenderId: '539777077394',
    projectId: 'instagram-cdabc',
    storageBucket: 'instagram-cdabc.appspot.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyTouEQv0pC1CN39x-ztaYAjW91mAjeeA',
    appId: '1:539777077394:ios:787031c435ad9ce061d64b',
    messagingSenderId: '539777077394',
    projectId: 'instagram-cdabc',
    storageBucket: 'instagram-cdabc.appspot.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxE8dTniE20e2XfQiJ5z_gIM1JI1-7y0s',
    appId: '1:539777077394:web:9394f4a57e292a9061d64b',
    messagingSenderId: '539777077394',
    projectId: 'instagram-cdabc',
    authDomain: 'instagram-cdabc.firebaseapp.com',
    storageBucket: 'instagram-cdabc.appspot.com',
  );
}
